name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  latex-test:
    name: Latex Test
    runs-on: ubuntu-22.04
    container:
      image: kjarosh/latex:2024.4
      options: --user root
    steps:
      - run: |
          apk update
          apk add --no-cache coreutils bash git make tar
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build LaTeX document
        run: |
          trap 'cat tex/*.log || true >> "$GITHUB_OUTPUT"' EXIT
          make -C tex
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp tex/*-draft.pdf deploy/
          echo "<html><body><a href="$(ls deploy)">Download Manuscript Draft [PDF]</a></body></html>" > deploy/index.html
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: tex/*-draft.pdf

  latex:
    name: Latex Build and Deploy
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    container:
      image: kjarosh/latex:2024.4
      options: --user root
    permissions:
      contents: write
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - run: |
          apk update
          apk add --no-cache coreutils bash git make tar
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Build LaTeX document
        run: |
          trap 'cat tex/*.log || true >> "$GITHUB_OUTPUT"' EXIT
          make -C tex
      - name: Prepare deploy directory
        run: |
          mkdir -p deploy
          cp tex/*-draft.pdf deploy/
          echo "<html><body><a href="$(ls deploy)">Download Manuscript Draft [PDF]</a></body></html>" > deploy/index.html
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  binder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ghostscript
          python3 -m pip install pip --upgrade
          python3 -m pip install -r requirements.txt
      # Adapted from https://askubuntu.com/a/524368
      - run: ./binder/execute_notebooks.sh
      # adapted from https://unix.stackexchange.com/a/545630
      - run: find -type f -name "*.pdf" -exec bash -c 'gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dBATCH -dQUIET -sOutputFile="new.pdf" "{}"; rm "{}"; mv "new.pdf" "{}";' {} \;
      - run: rm -rf .git
      - run: git init
      - uses: fregante/setup-git-user@v1
      - run: git commit --allow-empty -m "Initial commit"
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          branch: binder # The branch the action should deploy to.
          folder: "${{ github.workspace }}" # The folder the action should deploy.
